version: 1.0.{build}
configuration: Debug

before_build:
  - nuget restore

nuget:
  project_feed: true

build:
  project: Umbraco.Boilerplate.sln
  publish_azure: true
  publish_wap: true
  verbosity: normal